# Generated by Django 2.2b1 on 2019-05-28 19:56

import Panacea.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biennia', models.CharField(blank=True, choices=[('13-15', '13-15'), ('15-17', '15-17'), ('17-19', '17-19'), ('19-21', '19-21'), ('21-23', '21-23')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('address_line_1', models.CharField(blank=True, max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('classification', models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Small Urban', 'Small Urban'), ('Rural', 'Rural')], max_length=50, null=True)),
                ('vanshare_program', models.BooleanField(blank=True, null=True)),
                ('vanpool_expansion', models.BooleanField(blank=True, null=True)),
                ('in_jblm_area', models.BooleanField(blank=True, null=True)),
                ('in_puget_sound_area', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('random_field', models.CharField(blank=True, max_length=80)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', Panacea.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='vanpool_expansion_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vanpools_in_service_at_time_of_award', models.IntegerField(blank=True, null=True)),
                ('date_of_award', models.DateField(blank=True, null=True)),
                ('expansion_vans_awarded', models.IntegerField(blank=True, null=True)),
                ('latest_vehicle_acceptance', models.DateField(blank=True, null=True)),
                ('extension_granted', models.BooleanField(null=True)),
                ('expired', models.BooleanField(null=True)),
                ('notes', models.TextField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Panacea.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Other', 'Other')], default='Yearly', max_length=50)),
                ('due_date', models.DateField()),
                ('report_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_submitted', models.BooleanField(default=False)),
                ('profile_complete', models.BooleanField(default=False)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization')),
                ('reports_on', models.ManyToManyField(blank=True, to='Panacea.ReportType')),
            ],
        ),
        migrations.CreateModel(
            name='vanpool_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_year', models.IntegerField()),
                ('report_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('report_day', models.IntegerField(null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('vanshare_groups_in_operation', models.IntegerField(blank=True, null=True)),
                ('vanshare_group_starts', models.IntegerField(blank=True, null=True)),
                ('vanshare_group_folds', models.IntegerField(blank=True, null=True)),
                ('vanshare_passenger_trips', models.IntegerField(blank=True, null=True)),
                ('vanshare_miles_traveled', models.FloatField(blank=True, null=True)),
                ('vanpool_groups_in_operation', models.IntegerField(blank=True, null=True)),
                ('vanpool_group_starts', models.IntegerField(blank=True, null=True)),
                ('vanpool_group_folds', models.IntegerField(blank=True, null=True)),
                ('vans_available', models.IntegerField(blank=True, null=True)),
                ('loaner_spare_vans_in_fleet', models.IntegerField(blank=True, null=True)),
                ('vanpool_passenger_trips', models.IntegerField(blank=True, null=True)),
                ('vanpool_miles_traveled', models.FloatField(blank=True, null=True)),
                ('average_riders_per_van', models.FloatField(blank=True, null=True)),
                ('average_round_trip_miles', models.FloatField(blank=True, null=True)),
                ('data_change_explanation', models.CharField(blank=True, max_length=5000, null=True)),
                ('data_change_record', models.CharField(blank=True, max_length=10000, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization')),
                ('report_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.ReportType')),
            ],
            options={
                'unique_together': {('organization', 'report_year', 'report_month')},
            },
        ),
    ]
