# Generated by Django 2.2.6 on 2019-11-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffered',
            name='administration_of_mode',
            field=models.CharField(choices=[('Direct Operated', 'Direct Operated'), ('Purchased', 'Purchased')], max_length=80),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization'),
        ),
    ]
