# Generated by Django 2.2.6 on 2020-01-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit_mode',
            name='rollup',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
