# Generated by Django 2.1.7 on 2019-07-29 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalvanpool_expansion_analysis',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vanpools_in_service_at_time_of_award', models.IntegerField(blank=True, null=True)),
                ('date_of_award', models.DateField(blank=True, null=True)),
                ('expansion_vans_awarded', models.IntegerField(blank=True, null=True)),
                ('latest_vehicle_acceptance', models.DateField(blank=True, null=True)),
                ('extension_granted', models.BooleanField(null=True)),
                ('vanpool_goal_met', models.BooleanField(null=True)),
                ('expired', models.BooleanField(null=True)),
                ('notes', models.TextField(null=True)),
                ('awarded_biennium', models.CharField(blank=True, choices=[('11-13', '11-13'), ('13-15', '13-15'), ('15-17', '15-17'), ('17-19', '17-19'), ('19-21', '19-21'), ('21-23', '21-23'), ('23-25', '23-25'), ('25-27', '25-27')], max_length=50, null=True)),
                ('expansion_goal', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('service_goal_met_date', models.DateField(blank=True, null=True)),
                ('max_vanpool_numbers', models.IntegerField(blank=True, null=True)),
                ('max_vanpool_date', models.DateField(blank=True, null=True)),
                ('latest_vanpool_number', models.IntegerField(blank=True, null=True)),
                ('latest_report_date', models.DateField(blank=True, null=True)),
                ('months_remaining', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vanpool_expansion_analysis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalvanpool_report',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('report_year', models.IntegerField()),
                ('report_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('report_date', models.DateTimeField(default=None, null=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('vanshare_groups_in_operation', models.IntegerField(blank=True, null=True)),
                ('vanshare_group_starts', models.IntegerField(blank=True, null=True)),
                ('vanshare_group_folds', models.IntegerField(blank=True, null=True)),
                ('vanshare_passenger_trips', models.IntegerField(blank=True, null=True)),
                ('vanshare_miles_traveled', models.FloatField(blank=True, null=True)),
                ('vanpool_groups_in_operation', models.IntegerField(blank=True, null=True)),
                ('vanpool_group_starts', models.IntegerField(blank=True, null=True)),
                ('vanpool_group_folds', models.IntegerField(blank=True, null=True)),
                ('vans_available', models.IntegerField(blank=True, null=True)),
                ('loaner_spare_vans_in_fleet', models.IntegerField(blank=True, null=True)),
                ('vanpool_passenger_trips', models.IntegerField(blank=True, null=True)),
                ('vanpool_miles_traveled', models.FloatField(blank=True, null=True)),
                ('average_riders_per_van', models.FloatField(blank=True, null=True)),
                ('average_round_trip_miles', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vanpool_report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='biennia',
        ),
        migrations.RemoveField(
            model_name='vanpool_report',
            name='data_change_explanation',
        ),
        migrations.RemoveField(
            model_name='vanpool_report',
            name='data_change_record',
        ),
        migrations.RemoveField(
            model_name='vanpool_report',
            name='report_day',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_permissions_request',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='requested_permissions',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='awarded_biennium',
            field=models.CharField(blank=True, choices=[('11-13', '11-13'), ('13-15', '13-15'), ('15-17', '15-17'), ('17-19', '17-19'), ('19-21', '19-21'), ('21-23', '21-23'), ('23-25', '23-25'), ('25-27', '25-27')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='expansion_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='latest_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='latest_vanpool_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='max_vanpool_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='max_vanpool_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='months_remaining',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='service_goal_met_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='vanpool_goal_met',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='report_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalvanpool_report',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.organization'),
        ),
        migrations.AddField(
            model_name='historicalvanpool_report',
            name='report_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvanpool_report',
            name='report_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.ReportType'),
        ),
        migrations.AddField(
            model_name='historicalvanpool_expansion_analysis',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.organization'),
        ),
    ]
