# Generated by Django 2.2.5 on 2019-10-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='community_medicaid_days_of_service',
            new_name='days_of_service',
        ),
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='community_medicaid_revenue_service_vehicles',
            new_name='revenue_service_vehicles',
        ),
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='community_medicaid_service_and_eligibility',
            new_name='service_and_eligibility',
        ),
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='tax_authorized_description',
            new_name='tax_rate_description',
        ),
    ]
