# Generated by Django 2.2.6 on 2019-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit_mode',
            name='name',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
