# Generated by Django 2.2.5 on 2019-09-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cover_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_officer_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('executive_officer_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('executive_officer_title', models.CharField(blank=True, max_length=50, null=True)),
                ('service_website_url', models.CharField(blank=True, max_length=50, null=True)),
                ('service_area_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('congressional_districts', models.CharField(blank=True, max_length=50, null=True)),
                ('legislative_districts', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_government', models.CharField(blank=True, max_length=50, null=True)),
                ('governing_body', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_authorized_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('transit_development_plan_url', models.CharField(blank=True, max_length=50, null=True)),
                ('intermodal_connections', models.CharField(blank=True, max_length=50, null=True)),
                ('fares_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('community_medicaid_service_and_eligibility', models.CharField(blank=True, max_length=50, null=True)),
                ('current_operations', models.CharField(blank=True, max_length=50, null=True)),
                ('community_medicaid_revenue_service_vehicles', models.CharField(blank=True, max_length=50, null=True)),
                ('community_medicaid_days_of_service', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
