# Generated by Django 2.1.7 on 2019-09-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='summary_organization_classifications',
        ),
    ]
