# Generated by Django 2.2.6 on 2020-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover_sheet',
            name='intermodal_connections',
            field=models.TextField(blank=True, null=True, verbose_name='Connections to other systems'),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='published_version',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcover_sheet',
            name='intermodal_connections',
            field=models.TextField(blank=True, null=True, verbose_name='Connections to other systems'),
        ),
        migrations.AlterField(
            model_name='historicalcover_sheet',
            name='published_version',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='summary_organization_progress',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_status'),
        ),
    ]
