# Generated by Django 2.2b1 on 2019-06-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='biennia',
        ),
        migrations.RemoveField(
            model_name='vanpool_report',
            name='report_day',
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='report_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
