# Generated by Django 2.2.13 on 2021-05-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsummary_report_status',
            name='last_update_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='summary_report_status',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
