# Generated by Django 2.1.7 on 2019-03-27 22:46

import Panacea.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Panacea.models.CustomUserManager()),
            ],
        ),
    ]
