# Generated by Django 2.2.6 on 2020-09-23 17:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalvanpool_report',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('report_year', models.IntegerField()),
                ('report_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('report_date', models.DateTimeField(default=None, null=True)),
                ('vanshare_groups_in_operation', models.IntegerField(blank=True, null=True)),
                ('vanshare_group_starts', models.IntegerField(blank=True, null=True)),
                ('vanshare_group_folds', models.IntegerField(blank=True, null=True)),
                ('vanshare_passenger_trips', models.IntegerField(blank=True, null=True)),
                ('vanshare_miles_traveled', models.FloatField(blank=True, null=True)),
                ('vanpool_groups_in_operation', models.IntegerField(blank=True, null=True)),
                ('vanpool_group_starts', models.IntegerField(blank=True, null=True)),
                ('vanpool_group_folds', models.IntegerField(blank=True, null=True)),
                ('vans_available', models.IntegerField(blank=True, null=True)),
                ('loaner_spare_vans_in_fleet', models.IntegerField(blank=True, null=True)),
                ('vanpool_passenger_trips', models.IntegerField(blank=True, null=True)),
                ('vanpool_miles_traveled', models.FloatField(blank=True, null=True)),
                ('average_riders_per_van', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15)])),
                ('average_round_trip_miles', models.FloatField(blank=True, null=True)),
                ('frequency_of_claims', models.FloatField(blank=True, null=True)),
                ('operating_cost', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.organization')),
                ('report_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.ReportType')),
            ],
            options={
                'verbose_name': 'historical vanpool_report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
