# Generated by Django 2.1.7 on 2019-07-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='biennia',
        ),
        migrations.RemoveField(
            model_name='vanpool_report',
            name='report_day',
        ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='active_permissions_request',
        #     field=models.BooleanField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='requested_permissions',
        #     field=models.ManyToManyField(to='auth.Group'),
        # ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='awarded_biennium',
            field=models.CharField(blank=True, choices=[('11-13', '11-13'), ('13-15', '13-15'), ('15-17', '15-17'), ('17-19', '17-19'), ('19-21', '19-21'), ('21-23', '21-23'), ('23-25', '23-25'), ('25-27', '25-27')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='expansion_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='latest_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='latest_vanpool_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='max_vanpool_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='max_vanpool_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='months_remaining',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='service_goal_met_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='vanpool_goal_met',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='report_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
