# Generated by Django 2.1.7 on 2019-09-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_remove_organization_summary_organization_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='summary_organization_classifications',
            field=models.CharField(blank=True, choices=[('Community Provider', 'Community Provider'), ('Ferry', 'Ferry'), ('Intercity Bus', 'Intercity Bus'), ('Medicaid Broker', 'Medicaid Broker'), ('Monorail', 'Monorail'), ('Transit', 'Transit'), ('Tribe', 'Tribe')], max_length=50, null=True),
        ),
    ]
