# Generated by Django 2.2b1 on 2019-06-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20190607_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanpool_expansion_analysis',
            name='notes',
        ),
    ]
