# Generated by Django 2.2.6 on 2020-05-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20200423_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_offered',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization'),
        ),
        migrations.AlterField(
            model_name='service_offered',
            name='transit_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Panacea.transit_mode'),
        ),
    ]
