# Generated by Django 2.1.7 on 2019-06-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20190618_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_permissions_request',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
