# Generated by Django 2.1.7 on 2019-03-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20190327_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='FirstName',
            field=models.CharField(default='TestName', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='LastName',
            field=models.CharField(default='TestName', max_length=80),
            preserve_default=False,
        ),
    ]
