# Generated by Django 2.2.13 on 2021-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20210517_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='wsdot_managed_ntd_reporter',
            field=models.BooleanField(default=False),
        ),
    ]
