# Generated by Django 2.1.7 on 2019-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20190411_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='report_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='reports_on',
            field=models.ManyToManyField(blank=True, null=True, to='Panacea.ReportType'),
        ),
    ]
