# Generated by Django 2.2.6 on 2020-01-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_transit_mode_rollup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transit_mode',
            old_name='rollup',
            new_name='rollup_mode',
        ),
    ]
