# Generated by Django 2.2.6 on 2019-11-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20191108_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollup_mode',
            old_name='rollup_mode',
            new_name='name',
        ),
    ]
