# Generated by Django 2.2.6 on 2019-11-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_auto_20191105_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsummaryexpenses',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summaryexpenses',
            name='year',
            field=models.IntegerField(),
        ),
    ]
