# Generated by Django 2.2.6 on 2019-11-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20191108_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransit_data',
            old_name='mode',
            new_name='transit_mode',
        ),
        migrations.RenameField(
            model_name='transit_data',
            old_name='mode',
            new_name='transit_mode',
        ),
    ]
