# Generated by Django 2.2.5 on 2019-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20190917_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_sheet',
            name='monorail_ownership',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cover_sheet',
            name='organization_logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='community_medicaid_days_of_service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='community_medicaid_revenue_service_vehicles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='community_medicaid_service_and_eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='current_operations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='fares_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='governing_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='intermodal_connections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
