# Generated by Django 2.2.6 on 2019-11-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20191105_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsummarytransitdata',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsummarytransitdata',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summarytransitdata',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarytransitdata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
