# Generated by Django 2.2.6 on 2020-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20200501_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover_sheet',
            name='executive_officer_title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cover_sheet',
            name='tax_rate_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcover_sheet',
            name='executive_officer_title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcover_sheet',
            name='tax_rate_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
