# Generated by Django 2.2b1 on 2019-06-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_remove_vanpool_expansion_analysis_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
