# Generated by Django 2.2.6 on 2020-01-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20200113_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit_data',
            name='rollup_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Panacea.rollup_mode'),
        ),
    ]
