# Generated by Django 2.2.6 on 2020-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20201002_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit_metrics',
            name='order_in_summary',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
