# Generated by Django 2.1.7 on 2019-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20190411_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
