# Generated by Django 2.1.7 on 2019-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Panacea', '0003_profile_active_permissions_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_permissions',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
