# Generated by Django 2.1.7 on 2019-03-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_auto_20190327_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='LastName',
        ),
    ]
