# Generated by Django 2.2.6 on 2020-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_remove_fund_balance_type_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_balance_type',
            name='heading',
            field=models.CharField(default='Ending Balances, December 31', max_length=50),
        ),
    ]
