# Generated by Django 2.2.6 on 2019-11-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_auto_20191108_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffered',
            old_name='mode',
            new_name='transit_mode',
        ),
    ]
