# Generated by Django 2.1.7 on 2019-04-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_profile_profile_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='vanpool_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_year', models.IntegerField()),
                ('report_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('report_date', models.DateField()),
                ('vanshare_groups_in_operation', models.IntegerField(blank=True)),
                ('vanshare_group_starts', models.IntegerField(blank=True)),
                ('vanshare_group_folds', models.IntegerField(blank=True)),
                ('vanshare_passenger_trips', models.IntegerField(blank=True)),
                ('vanshare_miles_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('vanpool_groups_in_operation', models.IntegerField(blank=True)),
                ('vanpool_group_starts', models.IntegerField(blank=True)),
                ('vanpool_group_folds', models.IntegerField(blank=True)),
                ('vans_available', models.IntegerField(blank=True)),
                ('loaner_spare_vans_in_fleet', models.IntegerField(blank=True)),
                ('vanpool_passenger_trips', models.IntegerField(blank=True)),
                ('vanpool_miles_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('average_riders_per_van', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('average_round_trip_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization')),
            ],
        ),
    ]
