# Generated by Django 2.2.6 on 2020-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_auto_20200505_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_source',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund_balance_type',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue_source',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transit_metrics',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
