# Generated by Django 2.2.6 on 2019-11-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_auto_20191105_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsummarytransitdata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarytransitdata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
