# Generated by Django 2.2.5 on 2019-09-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_auto_20190917_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='vanpool_program',
        ),
    ]
