# Generated by Django 2.2.13 on 2021-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_auto_20210616_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='report_summary_table_subpart',
            name='sub_heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
