# Generated by Django 2.2.6 on 2020-01-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_auto_20200113_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund_balance_type',
            old_name='fund_balance_type',
            new_name='name',
        ),
    ]
