# Generated by Django 2.2b1 on 2019-06-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0004_vanpool_expansion_analysis_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
    ]
