# Generated by Django 2.2.6 on 2020-02-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_fund_balance_type_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue_source',
            name='inactive_flag',
            field=models.BooleanField(default=False),
        ),
    ]
