# Generated by Django 2.1.7 on 2019-04-16 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_vanpool_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='report_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
