# Generated by Django 2.2.13 on 2021-06-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_auto_20210616_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_summary_table_subpart',
            name='description',
        ),
        migrations.AddField(
            model_name='report_summary_table',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
