# Generated by Django 2.2.6 on 2019-11-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_auto_20191108_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOffered',
            new_name='service_offered',
        ),
    ]
