# Generated by Django 2.2.5 on 2019-09-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_remove_organization_vanpool_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='vanpool_program',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
