# Generated by Django 2.2.6 on 2019-11-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_auto_20191105_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsummaryrevenues',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summaryrevenues',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
