# Generated by Django 2.2.6 on 2020-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_auto_20200505_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover_sheet',
            name='organization_logo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcover_sheet',
            name='organization_logo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
