# Generated by Django 2.2.5 on 2019-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_organization_vanpool_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
