# Generated by Django 2.2b1 on 2019-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_profile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='acknowledge_validation_errors',
            field=models.BooleanField(default=False),
        ),
    ]
