# Generated by Django 2.2.6 on 2019-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_auto_20191108_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary_organization_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Community provider', 'Community provider'), ('Ferry', 'Ferry'), ('Intercity bus', 'Intercity bus'), ('Medicaid broker', 'Medicaid broker'), ('Monorail', 'Monorail'), ('Transit', 'Transit'), ('Tribe', 'Tribe')], max_length=120)),
            ],
        ),
    ]
