# Generated by Django 2.2.6 on 2020-02-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_revenue_source_inactive_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund_balance',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='historicalfund_balance',
            name='heading',
        ),
        migrations.AlterField(
            model_name='revenue_source',
            name='inactive_flag',
            field=models.BooleanField(choices=[(True, 'inactive'), (False, 'active')], default=False),
        ),
    ]
