# Generated by Django 2.1.7 on 2019-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_vanpool_report_report_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
