# Generated by Django 2.2.13 on 2021-06-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_auto_20210616_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
