# Generated by Django 2.2.6 on 2019-11-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0006_auto_20191105_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit_metrics',
            name='form_masking_class',
            field=models.CharField(blank=True, choices=[('Int', 'Int'), ('Float', 'Float'), ('Money', 'Money')], max_length=25, null=True),
        ),
    ]
