# Generated by Django 2.2.6 on 2020-02-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0007_auto_20200224_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_balance',
            name='heading',
            field=models.CharField(blank=True, default='Ending Balances, December 31', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund_balance',
            name='heading',
            field=models.CharField(blank=True, default='Ending Balances, December 31', max_length=50, null=True),
        ),
    ]
