# Generated by Django 2.2b1 on 2019-06-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0007_vanpool_report_acknowledge_validation_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanpool_report',
            name='acknowledge_validation_errors',
        ),
    ]
