# Generated by Django 2.2.6 on 2019-11-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0007_summary_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='summary_organization_classifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Panacea.summary_organization_type'),
        ),
    ]
