# Generated by Django 2.2.5 on 2019-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0007_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.AddField(
            model_name='historicalvanpool_report',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vanpool_report',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
