# Generated by Django 2.2.13 on 2021-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0007_report_summary_table_subpart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_summary_table',
            name='report_summary_table_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('NOT IMPLEMENTED', 'NOT IMPLEMENTED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report_summary_table_subpart',
            name='sub_part_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('NOT IMPLEMENTED', 'NOT IMPLEMENTED')], max_length=100),
        ),
    ]
