# Generated by Django 2.2.13 on 2021-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0008_auto_20210622_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='calculate_percentage_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='round_using_form_masking_class',
            field=models.BooleanField(default=False),
        ),
    ]
