# Generated by Django 2.1.7 on 2019-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0008_auto_20190416_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='vanshare_program',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
