# Generated by Django 2.2.5 on 2019-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0008_auto_20190919_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvanpool_report',
            name='test',
        ),
        migrations.RemoveField(
            model_name='vanpool_report',
            name='test',
        ),
        migrations.AddField(
            model_name='historicalvanpool_expansion_analysis',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vanpool_expansion_analysis',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
