# Generated by Django 2.2.6 on 2019-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0008_auto_20191106_1323'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='summary_fund_balance',
            name='unique_source_report',
        ),
        migrations.AddConstraint(
            model_name='summary_fund_balance',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'specific_fund_balance_type'), name='unique_end_balance'),
        ),
    ]
