# Generated by Django 2.2.6 on 2020-03-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0009_auto_20200227_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_offered',
            name='service_mode_discontinued',
        ),
        migrations.RemoveField(
            model_name='stylesheets',
            name='cp_data',
        ),
        migrations.RemoveField(
            model_name='stylesheets',
            name='cp_revenue_federal',
        ),
        migrations.RemoveField(
            model_name='stylesheets',
            name='cp_revenue_source',
        ),
        migrations.CreateModel(
            name='tribal_reporters_permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('permission_to_publish_coversheet', models.BooleanField(default=False)),
                ('permission_to_publish_ntd_data', models.BooleanField(default=False, verbose_name='Permission to publish NTD data')),
                ('permission_to_publish_reported_data', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization')),
            ],
            options={
                'unique_together': {('year', 'organization')},
            },
        ),
    ]
