# Generated by Django 2.2.6 on 2019-11-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0009_auto_20191107_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ending_balance_categories',
        ),
        migrations.RemoveField(
            model_name='historicalending_balances',
            name='ending_balance_category',
        ),
        migrations.RemoveField(
            model_name='historicalending_balances',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalending_balances',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalending_balances',
            name='report_by',
        ),
        migrations.DeleteModel(
            name='ending_balances',
        ),
        migrations.DeleteModel(
            name='Historicalending_balances',
        ),
    ]
