# Generated by Django 2.2.6 on 2019-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0009_auto_20191113_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue_source',
            name='agency_classification',
            field=models.ManyToManyField(blank=True, to='Panacea.summary_organization_type'),
        ),
        migrations.RemoveField(
            model_name='transit_metrics',
            name='agency_classification',
        ),
        migrations.AddField(
            model_name='transit_metrics',
            name='agency_classification',
            field=models.ManyToManyField(blank=True, to='Panacea.summary_organization_type'),
        ),
    ]
