# Generated by Django 2.1.7 on 2019-04-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0009_organization_vanshare_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanpool_report',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
