# Generated by Django 2.2.13 on 2021-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0009_auto_20210622_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='sub_total_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
