# Generated by Django 2.2.5 on 2019-09-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0009_auto_20190919_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvanpool_expansion_analysis',
            name='test',
        ),
        migrations.RemoveField(
            model_name='vanpool_expansion_analysis',
            name='test',
        ),
    ]
