# Generated by Django 2.1.7 on 2019-04-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0010_auto_20190419_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='report_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Panacea.ReportType'),
            preserve_default=False,
        ),
    ]
