# Generated by Django 2.2.13 on 2021-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0010_report_summary_table_subpart_sub_total_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue_source',
            name='order_in_summary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
