# Generated by Django 2.2.6 on 2019-11-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0010_auto_20191107_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue_source',
            old_name='agency_funding_classification',
            new_name='agency_classification',
        ),
    ]
