# Generated by Django 2.2.5 on 2019-09-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0011_expensessource_historicalsummaryexpenses_historicalsummaryrevenues_historicalsummarytransitdata_reve'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_sheet',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization'),
        ),
    ]
