# Generated by Django 2.2.6 on 2019-11-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0011_auto_20191108_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsummarytransitdata',
            old_name='metric_value',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='summarytransitdata',
            old_name='metric_value',
            new_name='reported_value',
        ),
    ]
