# Generated by Django 2.2.6 on 2020-04-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0011_auto_20200325_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='random_field',
            new_name='saw_id',
        ),
    ]
