# Generated by Django 2.1.7 on 2019-04-19 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0011_vanpool_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='report_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
