# Generated by Django 2.2.13 on 2021-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0011_auto_20210901_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue_source',
            name='order_in_summary',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
