# Generated by Django 2.2.5 on 2019-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0012_cover_sheet_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='average_riders_per_van',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='average_round_trip_miles',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='vanpool_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='vanshare_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_riders_per_van',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_round_trip_miles',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanpool_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanshare_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
