# Generated by Django 2.2.13 on 2021-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0012_auto_20210901_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='display_sub_heading',
            field=models.BooleanField(default=False),
        ),
    ]
