# Generated by Django 2.2.6 on 2019-11-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0012_auto_20191108_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsummaryrevenues',
            old_name='specific_revenue_value',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='summaryrevenues',
            old_name='specific_revenue_value',
            new_name='reported_value',
        ),
    ]
