# Generated by Django 2.2.6 on 2019-11-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0013_auto_20191108_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsummaryexpenses',
            old_name='specific_expense_value',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='subfundexpenses',
            old_name='specific_expense_value',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='summaryexpenses',
            old_name='specific_expense_value',
            new_name='reported_value',
        ),
    ]
