# Generated by Django 2.1.7 on 2019-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0013_remove_vanpool_report_report_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='classification',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Small Urban', 'Small Urban'), ('Rural', 'Rural')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='in_jblm_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='in_puget_sound_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vanpool_report',
            unique_together={('organization', 'report_year', 'report_month')},
        ),
    ]
