# Generated by Django 2.2.5 on 2019-09-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0013_auto_20190920_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvanpool_report',
            old_name='updated_date',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='vanpool_report',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
