# Generated by Django 2.2.5 on 2019-09-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0014_auto_20190920_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvanpool_expansion_analysis',
            old_name='awarded_biennium',
            new_name='award_biennium',
        ),
        migrations.RenameField(
            model_name='vanpool_expansion_analysis',
            old_name='awarded_biennium',
            new_name='award_biennium',
        ),
    ]
