# Generated by Django 2.2.6 on 2019-11-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0014_auto_20191108_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depreciation',
            old_name='depreciation',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='historicaldepreciation',
            old_name='depreciation',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='historicalsummary_fund_balance',
            old_name='specific_fund_balance_value',
            new_name='reported_value',
        ),
        migrations.RenameField(
            model_name='summary_fund_balance',
            old_name='specific_fund_balance_value',
            new_name='reported_value',
        ),
    ]
