# Generated by Django 2.2.13 on 2021-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0014_auto_20211006_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_summary_table_subpart',
            name='order',
            field=models.FloatField(null=True),
        ),
    ]
