# Generated by Django 2.2.5 on 2019-09-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0015_auto_20190920_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransitMode',
            new_name='transit_mode',
        ),
    ]
