# Generated by Django 2.1.7 on 2019-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0015_auto_20190507_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanpool_miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
