# Generated by Django 2.1.7 on 2019-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0016_auto_20190508_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_riders_per_van',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_round_trip_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanshare_miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
