# Generated by Django 2.2.5 on 2019-09-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0018_auto_20190920_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevenueSource',
            new_name='revenue_source',
        ),
    ]
