# Generated by Django 2.1.7 on 2019-05-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0018_profile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='data_change_explanation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
