# Generated by Django 2.1.7 on 2019-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0019_vanpool_report_data_change_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpool_report',
            name='data_change_record',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
