# Generated by Django 2.2.5 on 2019-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0019_auto_20190920_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='average_riders_per_van',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='average_round_trip_miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='vanpool_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='vanshare_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_riders_per_van',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_round_trip_miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanpool_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanshare_miles_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
