# Generated by Django 2.2.5 on 2019-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0020_auto_20190920_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='average_riders_per_van',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='average_round_trip_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='vanpool_miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvanpool_report',
            name='vanshare_miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_riders_per_van',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='average_round_trip_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanpool_miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanpool_report',
            name='vanshare_miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
