# Generated by Django 2.2.5 on 2019-09-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0021_auto_20190920_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='fares_desc',
            new_name='fares_description',
        ),
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='service_area_desc',
            new_name='service_area_description',
        ),
        migrations.RenameField(
            model_name='cover_sheet',
            old_name='tax_authorized_desc',
            new_name='tax_authorized_description',
        ),
    ]
